<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;

class BuildingResourceTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('building_resource')->insert([
            ['building_id' => 1, 'resource_id' => 1, 'cost' => 600,     'output' => 300,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 1, 'resource_id' => 2, 'cost' => 2000,    'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 1, 'resource_id' => 4, 'cost' => 0,       'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 1, 'resource_id' => 5, 'cost' => 1,       'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 1, 'resource_id' => 7, 'cost' => 5000,    'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 2, 'resource_id' => 1, 'cost' => 3600,    'output' => 900,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 2, 'resource_id' => 2, 'cost' => 12000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 2, 'resource_id' => 4, 'cost' => 0,       'output' => -20,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 2, 'resource_id' => 5, 'cost' => 2,       'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 2, 'resource_id' => 7, 'cost' => 40000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 3, 'resource_id' => 1, 'cost' => 72000,   'output' => 9000,   'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 3, 'resource_id' => 2, 'cost' => 240000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 3, 'resource_id' => 4, 'cost' => 0,       'output' => -60,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 3, 'resource_id' => 5, 'cost' => 6,       'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 3, 'resource_id' => 7, 'cost' => 200000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 4, 'resource_id' => 1, 'cost' => 75000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 50, 'refund_on_completion' => 0],
            ['building_id' => 4, 'resource_id' => 2, 'cost' => 50000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 4, 'resource_id' => 4, 'cost' => 0,       'output' => -40,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 4, 'resource_id' => 5, 'cost' => 2,       'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 4, 'resource_id' => 7, 'cost' => 100000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 5, 'resource_id' => 1, 'cost' => 3000,    'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 5, 'resource_id' => 2, 'cost' => 400,     'output' => 200,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 5, 'resource_id' => 4, 'cost' => 0,       'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 5, 'resource_id' => 5, 'cost' => 1,       'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 5, 'resource_id' => 7, 'cost' => 5000,    'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 6, 'resource_id' => 1, 'cost' => 18000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 6, 'resource_id' => 2, 'cost' => 2400,    'output' => 600,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 6, 'resource_id' => 4, 'cost' => 0,       'output' => -20,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 6, 'resource_id' => 5, 'cost' => 2,       'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 6, 'resource_id' => 7, 'cost' => 40000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 7, 'resource_id' => 1, 'cost' => 360000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 7, 'resource_id' => 2, 'cost' => 48000,   'output' => 6000,   'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 7, 'resource_id' => 4, 'cost' => 0,       'output' => -60,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 7, 'resource_id' => 5, 'cost' => 6,       'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 7, 'resource_id' => 7, 'cost' => 200000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 8, 'resource_id' => 1, 'cost' => 75000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 8, 'resource_id' => 2, 'cost' => 50000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 50, 'refund_on_completion' => 0],
            ['building_id' => 8, 'resource_id' => 4, 'cost' => 0,       'output' => -40,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 8, 'resource_id' => 5, 'cost' => 2,       'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 8, 'resource_id' => 7, 'cost' => 100000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 9, 'resource_id' => 1, 'cost' => 1500,    'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 9, 'resource_id' => 2, 'cost' => 1000,    'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 9, 'resource_id' => 3, 'cost' => 0,       'output' => 100,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 9, 'resource_id' => 4, 'cost' => 0,       'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 9, 'resource_id' => 5, 'cost' => 1,       'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 9, 'resource_id' => 7, 'cost' => 5000,    'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 10, 'resource_id' => 1, 'cost' => 9000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 10, 'resource_id' => 2, 'cost' => 6000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 10, 'resource_id' => 3, 'cost' => 0,      'output' => 300,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 10, 'resource_id' => 6, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 10, 'resource_id' => 7, 'cost' => 40000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 11, 'resource_id' => 1, 'cost' => 180000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 11, 'resource_id' => 2, 'cost' => 120000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 11, 'resource_id' => 3, 'cost' => 0,      'output' => 3000,   'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 11, 'resource_id' => 4, 'cost' => 0,      'output' => -60,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 11, 'resource_id' => 6, 'cost' => 6,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 11, 'resource_id' => 7, 'cost' => 200000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 12, 'resource_id' => 1, 'cost' => 75000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 12, 'resource_id' => 2, 'cost' => 50000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 12, 'resource_id' => 3, 'cost' => 0,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 50, 'refund_on_completion' => 0],
            ['building_id' => 12, 'resource_id' => 4, 'cost' => 0,      'output' => -40,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 12, 'resource_id' => 5, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 12, 'resource_id' => 7, 'cost' => 100000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 13, 'resource_id' => 1, 'cost' => 1500,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 13, 'resource_id' => 2, 'cost' => 1000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 13, 'resource_id' => 4, 'cost' => 0,      'output' => 100,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 13, 'resource_id' => 5, 'cost' => 1,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 13, 'resource_id' => 7, 'cost' => 5000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 14, 'resource_id' => 1, 'cost' => 9000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 14, 'resource_id' => 2, 'cost' => 6000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 14, 'resource_id' => 4, 'cost' => 0,      'output' => 300,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 14, 'resource_id' => 6, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 14, 'resource_id' => 7, 'cost' => 40000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 15, 'resource_id' => 1, 'cost' => 180000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 15, 'resource_id' => 2, 'cost' => 120000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 15, 'resource_id' => 4, 'cost' => 0,      'output' => 3000,   'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 15, 'resource_id' => 6, 'cost' => 6,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 15, 'resource_id' => 7, 'cost' => 200000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 16, 'resource_id' => 1, 'cost' => 75000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 16, 'resource_id' => 2, 'cost' => 50000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 16, 'resource_id' => 4, 'cost' => 0,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 50, 'refund_on_completion' => 0],
            ['building_id' => 16, 'resource_id' => 5, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 16, 'resource_id' => 7, 'cost' => 100000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 17, 'resource_id' => 1, 'cost' => 30000,  'output' => 300,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 17, 'resource_id' => 2, 'cost' => 20000,  'output' => 200,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 17, 'resource_id' => 3, 'cost' => 0,      'output' => 100,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 17, 'resource_id' => 4, 'cost' => 0,      'output' => 100,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 17, 'resource_id' => 7, 'cost' => 50000,  'output' => 0,      'single_output' => null, 'stores' => 50000, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 18, 'resource_id' => 1, 'cost' => 60000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 18, 'resource_id' => 2, 'cost' => 40000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 18, 'resource_id' => 5, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 18, 'resource_id' => 7, 'cost' => 40000,  'output' => 0,      'single_output' => null, 'stores' => 100000, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 19, 'resource_id' => 1, 'cost' => 120000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 19, 'resource_id' => 2, 'cost' => 80000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 19, 'resource_id' => 5, 'cost' => 4,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 19, 'resource_id' => 7, 'cost' => 160000, 'output' => 0,      'single_output' => null, 'stores' => 200000, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 20, 'resource_id' => 1, 'cost' => 4800,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 20, 'resource_id' => 2, 'cost' => 3600,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 20, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 20, 'resource_id' => 5, 'cost' => 1,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 20, 'resource_id' => 7, 'cost' => 25000,  'output' => 0,      'single_output' => null, 'stores' => 50000, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 21, 'resource_id' => 1, 'cost' => 4800,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 21, 'resource_id' => 2, 'cost' => 3600,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 21, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 21, 'resource_id' => 6, 'cost' => 1,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 21, 'resource_id' => 7, 'cost' => 25000,  'output' => 0,      'single_output' => null, 'stores' => 50000, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 22, 'resource_id' => 1, 'cost' => 12000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 22, 'resource_id' => 2, 'cost' => 8000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 22, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 22, 'resource_id' => 5, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 22, 'resource_id' => 7, 'cost' => 10000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0.5, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 23, 'resource_id' => 1, 'cost' => 36000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 23, 'resource_id' => 2, 'cost' => 16000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 23, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 23, 'resource_id' => 5, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 23, 'resource_id' => 7, 'cost' => 20000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0.5, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 24, 'resource_id' => 1, 'cost' => 24000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 24, 'resource_id' => 2, 'cost' => 16000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 24, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 24, 'resource_id' => 5, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 24, 'resource_id' => 7, 'cost' => 25000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 24, 'resource_id' => 9, 'cost' => 0,      'output' => 0,      'single_output' => null, 'stores' => 5000, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 25, 'resource_id' => 1, 'cost' => 15000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 25, 'resource_id' => 2, 'cost' => 10000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 25, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 25, 'resource_id' => 5, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 25, 'resource_id' => 7, 'cost' => 25000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 26, 'resource_id' => 1, 'cost' => 39000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 26, 'resource_id' => 2, 'cost' => 26000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 26, 'resource_id' => 4, 'cost' => 0,      'output' => -20,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 26, 'resource_id' => 6, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 26, 'resource_id' => 7, 'cost' => 40000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 27, 'resource_id' => 1, 'cost' => 156000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 27, 'resource_id' => 2, 'cost' => 104000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 27, 'resource_id' => 4, 'cost' => 0,      'output' => -40,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 27, 'resource_id' => 6, 'cost' => 4,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 27, 'resource_id' => 7, 'cost' => 160000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 28, 'resource_id' => 1, 'cost' => 33000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 28, 'resource_id' => 2, 'cost' => 22000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 28, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 28, 'resource_id' => 6, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 28, 'resource_id' => 7, 'cost' => 40000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 29, 'resource_id' => 1, 'cost' => 48000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 29, 'resource_id' => 2, 'cost' => 32000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 29, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 29, 'resource_id' => 6, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 29, 'resource_id' => 7, 'cost' => 60000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 30, 'resource_id' => 1, 'cost' => 144000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 30, 'resource_id' => 2, 'cost' => 96000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 30, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 30, 'resource_id' => 6, 'cost' => 4,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 30, 'resource_id' => 7, 'cost' => 240000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 31, 'resource_id' => 1, 'cost' => 30000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 31, 'resource_id' => 2, 'cost' => 20000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 31, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 31, 'resource_id' => 5, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 31, 'resource_id' => 7, 'cost' => 50000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 32, 'resource_id' => 1, 'cost' => 90000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 32, 'resource_id' => 2, 'cost' => 60000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 32, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 32, 'resource_id' => 5, 'cost' => 4,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 32, 'resource_id' => 7, 'cost' => 200000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 33, 'resource_id' => 1, 'cost' => 12000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 33, 'resource_id' => 2, 'cost' => 8000,   'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 33, 'resource_id' => 4, 'cost' => 0,      'output' => -10,    'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 33, 'resource_id' => 5, 'cost' => 2,      'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 33, 'resource_id' => 7, 'cost' => 25000,  'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 33, 'resource_id' => 8, 'cost' => 0,      'output' => 0,      'single_output' => null, 'stores' => 250000, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 34, 'resource_id' => 5, 'cost' => 0,      'output' => 1,      'single_output' => 1,    'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 34, 'resource_id' => 7, 'cost' => 100000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],
            ['building_id' => 35, 'resource_id' => 6, 'cost' => 0,      'output' => 1,      'single_output' => 1,    'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 0],
            ['building_id' => 35, 'resource_id' => 7, 'cost' => 100000, 'output' => 0,      'single_output' => null, 'stores' => 0, 'interest' => 0, 'abundance' => 0, 'refund_on_completion' => 1],

        ]);
    }
}
