<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UnitTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('units')->insert([
            [
                'name'           => 'Fighter',
                'drive'          => 1,
                'turns'          => 4,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Bomber',
                'drive'          => 1,
                'turns'          => 6,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Frigate',
                'drive'          => 2,
                'turns'          => 10,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Destroyer',
                'drive'          => 2,
                'turns'          => 14,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Cruiser',
                'drive'          => 3,
                'turns'          => 20,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Battleship',
                'drive'          => 3,
                'turns'          => 26,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Freighter',
                'drive'          => 1,
                'turns'          => 8,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Merchant',
                'drive'          => 2,
                'turns'          => 10,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Trader',
                'drive'          => 3,
                'turns'          => 16,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Hulk',
                'drive'          => 3,
                'turns'          => 20,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Invasion Ship',
                'drive'          => 1,
                'turns'          => 16,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 1,
                'can_colonise'   => 0,
                'hp'             => 0,
                'ap'             => 0,
            ],
            [
                'name'           => 'Outpost Ship',
                'drive'          => 1,
                'turns'          => 16,
                'max_per_ruler'  => null,
                'max_per_fleet'   => null,
                'max_per_planet' => null,
                'can_invade'     => 0,
                'can_colonise'   => 1,
                'hp'             => 0,
                'ap'             => 0,
            ],
        ]);
    }
}
